# Generated by Django 6.0.2 on 2026-03-26 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_menudetails_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Non défini', max_length=255)),
                ('last_name', models.CharField(default='Non défini', max_length=255)),
                ('sold', models.FloatField(default=0.0)),
                ('class_name', models.CharField(default='Inconnu', max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('respo', 'Responsable'), ('student', 'Étudiant')], default='student', max_length=50)),
                ('status', models.CharField(choices=[('cotisant', 'Cotisant'), ('non_cotisant', 'Non Cotisant'), ('prof', 'Professeur')], default='non_cotisant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cash',
        ),
        migrations.RemoveField(
            model_name='users_custom',
            name='user',
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
        migrations.DeleteModel(
            name='users_custom',
        ),
    ]
