# Generated by Django 6.0.2 on 2026-04-09 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercustom_delete_cash_remove_users_custom_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_cash', models.FloatField()),
                ('gain_card', models.FloatField()),
                ('gain_cash', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='usercustom',
            name='nb_transaction',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.article')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
