# Generated by Django 6.0.2 on 2026-04-09 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cash_usercustom_nb_transaction_transactiondetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='price',
            new_name='price_cotisant',
        ),
        migrations.AddField(
            model_name='article',
            name='price_non_cotisant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('le midi', 'Le Midi'), ('boisson', 'Boisson'), ('snack', 'Snack'), ('viennoiseries', 'Viennoiseries')], default='snack', max_length=50),
        ),
        migrations.CreateModel(
            name='users_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='No Defined', max_length=255)),
                ('last_name', models.CharField(default='No Defined', max_length=255)),
                ('sold', models.FloatField(default=0)),
                ('class_name', models.CharField(default='No Defined', max_length=255)),
                ('nb_transaction', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('respo', 'Responsable'), ('student', 'Étudiant')], default='student', max_length=50)),
                ('status', models.CharField(choices=[('cotisant', 'Cotisant'), ('non_cotisant', 'Non Cotisant'), ('prof', 'Professeur')], default='non_cotisant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
