# Generated by Django 6.0.2 on 2026-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_price_article_price_cotisant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('le_midi', 'Le Midi'), ('boisson', 'Boisson'), ('snack', 'Snack'), ('viennoiseries', 'Viennoiseries')], default='snack', max_length=50),
        ),
    ]
