# Generated by Django 6.0.2 on 2026-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_custom',
            name='nfc_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UID carte NFC'),
        ),
    ]
